import StoreProvider from "@/lib/StoreProvider";
import type { Metadata } from "next";
import { Raleway, Lora, Nunito } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-raleway',
})

const lora = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lora',
})

const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider
      selectedDay={0}
      isSidenavOpen={false}
    >
      <html lang="en">
        <body className={`${raleway.variable} ${lora.variable} ${nunito.variable}`}>{children}</body>
      </html>
    </StoreProvider>

  );
}
